socialmedia/users/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms.validators import (DataRequired,
                                ValidationError,
                                EqualTo,
                                Length)
from wtforms import (StringField,
                     SubmitField,
                     PasswordField,
                     BooleanField,
                     SelectField,
                     TextAreaField)

from socialmedia.models import User


choices = (
    ('male', 'Male'),
    ('female', 'Female')
)


class UserCreationForm(FlaskForm):
    username = StringField('Username', validators=[
        DataRequired(),
        Length(min=2, max=20)
    ])
    email = StringField('Email', validators=[
        DataRequired()
    ])
    password = PasswordField('Password', validators=[
        DataRequired()
    ])
    confirm_password = PasswordField('Confirm Password', validators=[
        DataRequired(),
        EqualTo('password')
    ])
    submit = SubmitField('Submit')

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError('User already exists. Please select another')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError('User already exists. Please select another')


class LoginForm(FlaskForm):
    email = StringField('Email', validators=[
        DataRequired()
    ])
    password = PasswordField('Password', validators=[
        DataRequired()
    ])
    remember = BooleanField('Remember me')
    submit = SubmitField('Login')


class AccountInfo(FlaskForm):
    first_name = StringField('First name')
    last_name = StringField('Last Name')
    gender = SelectField('Gender', choices=choices)
    bio = TextAreaField('Bio')
    submit = SubmitField('Submit')
    username = StringField('Username', validators=[
        DataRequired(),
        Length(min=2, max=20)
    ])
    email = StringField('Email', validators=[
        DataRequired()
    ])
    password = PasswordField('Password', validators=[
        DataRequired()
    ])
    confirm_password = PasswordField('Confirm Password', validators=[
        DataRequired(),
        EqualTo('password')
    ])
    profile_image = FileField('Profile Picture', validators=[
        FileAllowed(['jpg', 'png'])
    ])


class RequestChangePassword(FlaskForm):
    email = StringField('Email Address', validators=[
        DataRequired()
    ])
    submit = SubmitField('Send reset link')

    def validate_email(self, email):
        user = User.query.filter_by(email=email).first()
        if user is None:
            return ValidationError('Email does not exist')
        return user


class ChangePasswordFormFromToken(FlaskForm):
    new_password = PasswordField('New Password', validators=[
        DataRequired()
    ])
    confirm_password = PasswordField('Confirm Password', validators=[
        DataRequired(),
        EqualTo('new_password')
    ])
    submit = SubmitField('Reset Password')

socialmedia/posts/routes.py
from flask_login import login_required, current_user
from flask import (flash,
                   redirect,
                   url_for,
                   render_template,
                   request,
                   Blueprint,
                   abort)
from .forms import PostCreationForm
from socialmedia.models import Post
from flask import current_app
from .utils import postsave_picture

posts = Blueprint('posts', __name__)


@posts.route('/createpost', methods=['GET', 'POST'])
@login_required
def post_create():
    form = PostCreationForm()
    if form.validate_on_submit() and form.post_image.data:
        picture_file = postsave_picture(form.post_image.data)
        post_image = picture_file
        post_title = form.post_title.data
        post_content = form.post_content.data
        create = Post(post_image=post_image, post_title=post_title, post_content=post_content, user_id=current_user.id)
        db.session.add(create)
        db.session.commit()
        flash('You have successfully created a new post', 'success')
        return redirect(url_for('main.home'))
    elif form.validate_on_submit():
        post_title = form.post_title.data
        post_content = form.post_content.data
        create = Post(post_title=post_title, post_content=post_content, user_id=current_user.id)
        db.session.add(create)
        db.session.commit()
        flash('You have successfully created a new post', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='Create Post', form=form)


@posts.route('/detail/<int:user_id>')
def detail_view(user_id):
    post_detail = Post.query.get_or_404(user_id)
    return render_template('detail.html', post_detail=post_detail)


@posts.route('/detail/update/<int:post_id>', methods=['GET', 'POST'])
@login_required
def update(post_id):
    post = Post.query.get_or_404(post_id)
    form = PostCreationForm()
    if post.author.id != current_user.id:
        abort(403)
    if request.method == 'POST':
        post.post_title = form.post_title.data
        post.post_content = form.post_content.data
        db.session.commit()
        return redirect(url_for('home'))
    elif request.method == 'GET':
        form.post_title.data = post.post_title
        form.post_content.data = post.post_title
    return render_template('update.html', post=post, form=form)


@posts.route('/detail/delete/<int:post_id>', methods=['GET', 'POST'])
@login_required
def delete(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author.id != current_user.id:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('You have deleted the post successfully', 'danger')
    return redirect(url_for('main.home'))

socialmedia/users/routes.py
from flask import request, render_template, redirect, Blueprint, url_for, flash
from flask_login import current_user, login_required, logout_user, login_user
from socialmedia import db
from socialmedia.models import Post, User
from .forms import (UserCreationForm,
                    LoginForm,
                    AccountInfo,
                    RequestChangePassword,
                    ChangePasswordFormFromToken)
from socialmedia import bcrypt
from .utils import send_reset_token, save_picture

users = Blueprint('users', __name__)


@users.route('/user_posts/<string:username>', methods=['GET', 'POST'])
def user_post(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page, per_page=1)
    return render_template('user.html', title=f"{user.username} Posts", posts=posts, user=user)


@users.route('/register', methods=['GET', 'POST'])
def register_user():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = UserCreationForm()
    if form.validate_on_submit():
        hashed_pasword = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_pasword)
        db.session.add(user)
        db.session.commit()
        flash('You have successfully created an account. You can now login', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', form=form, title='Register')


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            flash('You have logged in successfully', 'success')
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('home'))
        else:
            flash('Invalid Credentials', 'danger')
    return render_template('login.html', form=form)


@users.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have successfully logged out', 'success')
    return redirect(url_for('main.home'))


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    user = User.query.get(current_user.id)
    form = AccountInfo()
    profile_image = url_for('static', filename='profile_image/' + current_user.profile_image)
    if form.profile_image.data:
        picture_file = save_picture(form.profile_image.data)
        current_user.profile_image = picture_file

    if request.method == 'POST':
        user.first_name = form.first_name.data
        user.last_name = form.last_name.data
        user.bio = form.bio.data
        user.gender = form.gender.data
        user.email = form.email.data
        user.username = form.username.data
        db.session.commit()
        flash('You have successfully updated your profile', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.first_name.data = user.first_name
        form.last_name.data = user.last_name
        form.bio.data = user.bio
        form.gender.data = user.gender
        form.email.data = user.email
        form.username.data = user.username
    return render_template('account.html', title=current_user.username + ' ' + 'Account', profile_image=profile_image,
                           form=form)


@users.route('/reset_password', methods=['GET', 'POST'])
def reset_password():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestChangePassword
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is None:
            flash('User does not exist', 'danger')
            return redirect(url_for('reset_password'))
        send_reset_token(user)
        flash('Your reset link has being sent to the given email', 'success')
        return redirect(url_for('users.login'))
    render_template('request_change_password.html', title='Request Reset', form=form)


@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_token(token)
    if user is None:
        flash('That is an invalid token or expired', 'warning')
        return redirect(url_for('reset_request'))
    form = ChangePasswordFormFromToken
    if form.validate_on_submit():
        new_password = form.new_password.data
        confirm_password = form.confirm_password.data
        if new_password == confirm_password:
            new_hash = bcrypt.generate_password_hash(new_password)
            user.password = new_hash
            db.session.commit()
            return redirect(url_for('users.login'))
    return render_template('reset_token.html', form=form, title='Reset Password')

socialmedia/templates/account.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <img class="rounded-circle " width="13%" height="150px" src="{{profile_image}}">
    <h3>{{current_user.username}}</h3>
    <h3>{{current_user.email}}</h3>
</div>
    <form role="form" class="container form-horizontal m-50" method="POST" action="" enctype="multipart/form-data" >
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <div class="row">
                <div class="col-md-8 pd-10">
                <legend>
                    Update Profile
                </legend>
                    <div class="form-group">
                    {{ form.profile_image.label}}
                        {% if form.profile_image.errors %}
                            {{ form.profile_image(class="form-control-file form-control-lg is-invalid")}}
                            <div class="invalid-feedback">
                                {% for error in form.profile_image.errors %}
                                    <span>
                                        {{ error }}
                                    </span>
                                {% endfor %}
                            </div>
                        {%else%}
                            {{ form.profile_image(class="form-control-file form-control-lg")}}
                        {% endif %}
                    </div>
                    <div class="form-group">
                    {{ form.bio.label(class="form-control-label")}}
                        {% if form.bio.errors %}
                            {{ form.bio(class="form-control form-control-lg is-invalid")}}
                            <div class="invalid-feedback">
                                {% for error in form.bio.errors %}
                                    <span>
                                        {{ error }}
                                    </span>
                                {% endfor %}
                            </div>
                        {%else%}
                            {{ form.bio(class="form-control form-control-lg")}}
                        {% endif %}
                    </div>
                    <div class="form-group">
                    {{ form.first_name.label(class="form-control-label")}}
                        {% if form.first_name.errors %}
                            {{ form.first_name(class="form-control form-control-lg is-invalid")}}
                            <div class="invalid-feedback">
                                {% for error in form.first_name.errors %}
                                    <span>
                                        {{ error }}
                                    </span>
                                {% endfor %}
                            </div>
                        {%else%}
                            {{ form.first_name(class="form-control form-control-lg")}}
                        {% endif %}
                    </div>
                    <div class="form-group">
                    {{ form.last_name.label(class="form-control-label")}}
                        {% if form.last_name.errors %}
                            {{ form.last_name(class="form-control form-control-lg is-invalid")}}
                            <div class="invalid-feedback">
                                {% for error in form.last_name.errors %}
                                    <span>
                                        {{ error }}
                                    </span>
                                {% endfor %}
                            </div>
                        {%else%}
                            {{ form.last_name(class="form-control form-control-lg")}}
                        {% endif %}
                    </div>
                    <div class="form-group">
                    {{ form.gender.label(class="form-control-label")}}
                        {% if form.gender.errors %}
                            {{ form.gender(class="form-control form-control-lg is-invalid")}}
                            <div class="invalid-feedback">
                                {% for error in form.gender.errors %}
                                    <span>
                                        {{ error }}
                                    </span>
                                {% endfor %}
                            </div>
                        {%else%}
                            {{ form.gender(class="form-control form-control-lg")}}
                        {% endif %}
                    </div>
                    <div class="form-group">
                    {{ form.username.label(class="form-control-label")}}
                        {% if form.username.errors %}
                            {{ form.username(class="form-control form-control-lg is-invalid")}}
                            <div class="invalid-feedback">
                                {% for error in form.username.errors %}
                                    <span>
                                        {{ error }}
                                    </span>
                                {% endfor %}
                            </div>
                        {%else%}
                            {{ form.username(class="form-control form-control-lg")}}
                        {% endif %}
                    </div>
                    <div class="form-group">
                    {{ form.email.label(class="form-control-label")}}
                        {% if form.email.errors %}
                            {{ form.email(class="form-control form-control-lg is-invalid")}}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                    <span>
                                        {{ error }}
                                    </span>
                                {% endfor %}
                            </div>
                        {%else%}
                            {{ form.email(class="form-control form-control-lg")}}
                        {% endif %}
                    </div>
                    <div class="form-group">
                    <div>
                        {{ form.submit(class="btn btn-info btn-lg")}}
                    </div>
                </div>
            </div>
        </fieldset>
    </form>
{% endblock %}

socialmedia/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css')}}">

    {% if title %}
    <title>GP - {{title}}</title>
    {% else %}
    <title>Godspower Eze</title>
    {% endif %}
  </head>
  <body class="container-fluid">
  <nav class="navbar navbar-expand-lg navbar-light bg-primary">
      <a class="navbar-brand" href="{{ url_for('main.home')}}"><img class="rounded-circle pr-2" width="70px" src="{{ url_for('static', filename='mypicture.jpg')}}">Mini Social By Godspower Eze</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{{ url_for('main.home')}}">Home <span class="sr-only">(current)</span></a>
          </li>
            {% if current_user.is_authenticated %}
                <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.account')}}">My Account</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="{{ url_for('posts.post_create')}}">Create Post</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.logout')}}">Logout</a>
                </li>
            {% else %}
                <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.login')}}">Login</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.register_user')}}">Register</a>
                </li>
            {% endif %}

        </ul>
      </div>
    </nav>
        <div class="mt-2">
        {% with messages = get_flashed_messages(with_categories=true)%}
            {% if messages %}
              {% for category, message in messages %}
                  <div class="alert alert-{{category}}">
                    {{message}}
                  </div>
              {% endfor %}
            {% endif %}
        {% endwith %}
    </div>
    {% block content %}
    {% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js')}}"></script>
  </body>
</html>

socialmedia/templates/create_post.html
{% extends 'base.html' %}
{% block content %}
    <form role="form" class="container form-horizontal" method="POST" action="" action="" enctype="multipart/form-data" >
        {{ form.hidden_tag() }}
        <fieldset>
            <div class="row">
                <div class="col-md-8 pd-10">
                <legend>
                    Create Post
                </legend>
                    <div class="form-group">
                    {{ form.post_image.label}}
                        {% if form.post_image.errors %}
                            {{ form.post_image(class="form-control-file form-control-lg is-invalid")}}
                            <div class="invalid-feedback">
                                {% for error in form.post_image.errors %}
                                    <span>
                                        {{ error }}
                                    </span>
                                {% endfor %}
                            </div>
                        {%else%}
                            {{ form.post_image(class="form-control-file form-control-lg")}}
                        {% endif %}
                    </div>
                    <div class="form-group">
                    {{ form.post_title.label(class="form-control-label")}}
                    {{ form.post_title(class="form-control")}}
                    </div>
                    <div class="form-group">
                    {{ form.post_content.label(class="form-control-label")}}
                    {{ form.post_content(class="form-control")}}
                    </div>
                    <div>
                        {{ form.submit(class="btn btn-info btn-lg")}}
                    </div>
                </div>
            </div>
        </fieldset>
    </form>
{% endblock %}

socialmedia/templates/detail.html
{% extends 'base.html' %}
{% block content %}
<h1 class="container">
    {{ post_detail.post_title }}
</h1>
    <div class="container bg-info">
        <small class="text-right"><img class="rounded-circle pr-2 pt-2" width="50px" src="{{ url_for('posts.static', filename='mypicture.jpg')}}">By {{post_detail.author.username}}</small>
    <h3>{{ post_detail.post_title}}</h3>
        <hr color="black">
    <p class="lead">
        {{ post_detail.post_content }}
    </p>
        {% if post_detail.author.id == current_user.id %}
            <a class="btn btn-warning mr-2 mb-2" href="{{url_for('posts.update', post_id=post_detail.id)}}">Update</a>
            <a class="btn btn-danger mb-2" href="{{url_for('posts.delete', post_id=post_detail.id)}}">Delete</a>
        {% endif %}
     </div>
{% endblock %}

socialmedia/templates/home.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    <div class="col-md-8 center">
        <h1 class="container">
    Posts
</h1>
    {% for p in post.items %}
    <div class="container bg-info">
        <small class="text-right"><img class="rounded-circle pr-2 pt-2" width="50px" src="{{ url_for('static', filename='mypicture.jpg')}}"><a href="{{url_for('users.user_post', username=p.author.username )}}">By {{p.author.username}}</a></small>
        <h3><a href="{{ url_for('posts.detail_view', user_id=p.id)}}">{{ p.post_title}}</a></h3>
        {% if p.post_image%}
        <div>
            <img class="container" src="/static/post_image/{{p.post_image}}">
        </div>
        {% endif %}
        <hr color="black">
    <p class="container lead">
        {{ p.post_content }}
    </p>
     </div>
    {% endfor %}
    </div>
</div>
<div class="container">
{% for page_num in post.iter_pages(left_edge=1, right_edge=1,left_current=1, right_current=2) %}
        {% if page_num %}
            {% if post.page == page_num %}
                <a class="btn btn-info m-2" href="{{url_for('main.home', page=page_num)}}">
                    {{ page_num }}
                </a>
            {% else %}
                <a class="btn btn-outline-info m-2" href="{{url_for('main.home', page=page_num)}}">
                    {{ page_num }}
                </a>
            {% endif %}
        {% endif %}
    {% endfor %}
</div>
{% endblock %}

socialmedia/templates/login.html
 {% extends 'base.html' %}
{% block content %}
    <form role="form" class="container form-horizontal" method="POST" action="" >
        {{ form.hidden_tag() }}
        <fieldset>
            <div class="row">
                <div class="col-md-8 pd-10">
                <legend>
                    Login
                </legend>
                    <div class="form-group">
                    {{ form.email.label(class="form-control-label")}}
                        {% if form.email.errors %}
                            {{ form.email(class="form-control form-control-lg is-invalid")}}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                    <span>
                                        {{ error }}
                                    </span>
                                {% endfor %}
                            </div>
                        {%else%}
                            {{ form.email(class="form-control form-control-lg")}}
                        {% endif %}
                    </div>
                    <div class="form-group">
                    {{ form.password.label(class="form-control-label")}}
                        {% if form.password.errors %}
                            {{ form.password(class="form-control form-control-lg is-invalid")}}
                            <div class="invalid-feedback">
                                {% for error in form.password.errors %}
                                    <span>
                                        {{ error }}
                                    </span>
                                {% endfor %}
                            </div>
                        {%else%}
                            {{ form.password(class="form-control form-control-lg")}}
                        {% endif %}
                    </div>
                    <div class="form-check">
                    {{ form.remember(class="form-check-input")}}
                    {{ form.remember.label(class="form-check-label")}}
                    </div>
                    <div>
                        {{ form.submit(class="btn btn-info btn-lg")}}
                    </div>
                </div>
            </div>
        </fieldset>
    </form>
{% endblock %}

socialmedia/templates/update.html
{% extends 'base.html' %}
{% block content %}
    <form role="form" class="container form-horizontal" method="POST" action="" >
        {{ form.hidden_tag() }}
        <fieldset>
            <div class="row">
                <div class="col-md-8 pd-10">
                <legend>
                    Update Post
                </legend>
                <div class="form-group">
                    {{ form.post_title.label(class="form-control-label")}}
                    {{ form.post_title(class="form-control")}}
                    </div>
                    <div class="form-group">
                    {{ form.post_content.label(class="form-control-label")}}
                    {{ form.post_content(class="form-control")}}
                    </div>
                    <div>
                        {{ form.submit(class="btn btn-info btn-lg")}}
                    </div>
                </div>
            </div>
        </fieldset>
    </form>
{% endblock %}

socialmedia/templates/user.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    <div class="col-md-8 center">
        <h1 class="container">
            Posts by {{user.username}} {{posts.total}}
        </h1>
    {% for p in posts.items %}
    <div class="container bg-info">
        <small class="text-right"><img class="rounded-circle pr-2 pt-2" width="50px" src="{{ url_for('static', filename='mypicture.jpg')}}">By {{p.author.username}}</small>
        <h3><a href="{{ url_for('posts.detail_view', user_id=p.id)}}">{{ p.post_title}}</a></h3>
        {% if p.post_image%}
        <div>
            <img class="container" src="/static/post_image/{{p.post_image}}">
        </div>
        {% endif %}
        <hr color="black">
    <p class="container lead">
        {{ p.post_content }}
    </p>
     </div>
    {% endfor %}
    </div>
</div>
<div class="container">
{% for page_num in posts.iter_pages() %}
        {% if page_num %}
            <a class="btn btn-info m-2" href="{{url_for('main.home', page=page_num)}}">
                {{ page_num }}
            </a>
        {% endif %}
    {% endfor %}
</div>
{% endblock %}